### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by swagkarna** [ScRiPt1337/back_music_player#1]
when i run this command on win 7 i got this error
    backmusic "https://www.youtube.com/watch?v=AuGIHznyuXk"

error : canot specify path
when i run player.py . got this error 
please specify driver name in 79 characters and program quited

**Comment by ScRiPt1337** [comment]
> when i run this command on win 7 i got this error
> backmusic "https://www.youtube.com/watch?v=AuGIHznyuXk"
> 
> error : canot specify path
> when i run player.py . got this error
> please specify driver name in 79 characters and program quited

its only for linux bruh
